name: First workflow in repo

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
      - dev

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome
        run: echo "This is the first job in the repository and it will always run"
  
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: print comit message
        run: git log -1 --pretty=format:%B



