name: First workflow in repo

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

  push:
    branches:
      - main
  
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - dev

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome
        run: echo "This is the first job in the repository and it will always run"
  
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: print comit message
        run: |
          commitmsg=${{ github.event.head_commit.message }}
          echo $commitmsg




